name: Execução de testes regressivos DEVELOP

on:
  # push:
  #   branches: [ develop ]
  pull_request:
    branches: 
      - '*'
    types:
      - opened
      - synchronize
      # [ develop ]
  # schedule:
  #   - cron: '0 9,17,22 * * 1,2,3,4,5'

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: Setup Node.js enviroment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencias
        run: | 
          node -v
          npm install

      - name: Cypress run
        uses: cypress-io/github-action@v5 
        with:
          command: npm run tests
